apiVersion: v1
kind: Pod
metadata: 
  name: myapp-v1
  labels:
    app-type: backend
    app: myapp
spec:
  containers:
  - image: dhananjay01/myapp:latest
    name: myapp-v1
  imagePullSecrets: 
  - name: dockerhub-secrets
